# Generated by Django 3.0.7 on 2020-07-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='pick_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='spotify_playlist',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='vote_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='youtube_playlist',
            field=models.SlugField(null=True),
        ),
    ]
