# Generated by Django 3.0.7 on 2020-07-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20200705_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='spotify_playlist',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='youtube_playlist',
            field=models.URLField(null=True),
        ),
    ]
