# Generated by Django 3.0.7 on 2020-07-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20200705_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_by', models.CharField(max_length=280)),
                ('artist', models.CharField(max_length=280)),
                ('song', models.CharField(max_length=280)),
                ('spotify_track', models.URLField(null=True)),
                ('youtube_video', models.URLField(null=True)),
            ],
        ),
    ]
