# Generated by Django 3.0.7 on 2020-07-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_pick_contest_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('contest_id', 'picked_by'), name='unique_by_contest_and_picked_by'),
        ),
    ]
