# Generated by Django 3.0.7 on 2020-07-13 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20200706_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='pick_deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 2, 21, 46, 500972)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='vote_deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 2, 21, 46, 501015)),
        ),
    ]
