# Generated by Django 3.0.7 on 2020-07-13 03:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0007_auto_20200713_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='pick_deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 3, 35, 22, 309508)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='vote_deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 3, 35, 22, 309540)),
        ),
        migrations.AlterField(
            model_name='pick',
            name='contest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.Contest'),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='league_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.League'),
        ),
    ]
